sudo: required
services:
  - docker

before_install:
  - docker build -t jsb13207/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jsb13207/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-testing"
  env: "DockerReactTesting-env"
  bucket_name: "elasticbeanstalk-us-west-2-682989964183"
  bucket_path: "docker-react-testing"
  on:
    branch: master
  access_key_id: $AWS_access_key
  secret_access_key:
    secure: "$AWS_secret_key"
